### ISSUE TITLE
leaked connection

### ISSUE THREAD

**Issue by jtjeferreira** [kamon-io/kamon-zipkin#2]
Got this warning in my logs

```
[warn] o.OkHttpClient - A connection to http://localhost:9411/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:143)
	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:78)
	at okhttp3.RealCall.execute(RealCall.java:66)
	at zipkin2.reporter.okhttp3.HttpCall.execute(HttpCall.java:35)
	at zipkin2.reporter.okhttp3.HttpCall.execute(HttpCall.java:26)
	at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:272)
	at zipkin2.reporter.AsyncReporter$Builder$1.run(AsyncReporter.java:179)
```

**Comment by ivantopo** [comment]
related to https://github.com/openzipkin/zipkin-reporter-java/issues/89
